---
- name: add repos
  yum:
    name: epel-release

- name: install nginx
  yum:
    name: nginx

- name: add nginx conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: start nginx service
  service:
    name: nginx
    state: restarted