---
- name: add repos
  yum:
    name: epel-release
    
- name: install python3
  yum:
    name: python3

- name: install pip3
  yum:
    name: python-pip

- name: install python setup tools
  yum:
    name: python-setuptools
  
- name: install virtualenv
  pip:
    name: virtualenv