---
- name: download install script
  get_url: url=https://get.docker.com/ dest=/tmp/docker.sh

- name: install docker
  command: /bin/sh /tmp/docker.sh

- name: start docker
  systemd:
    name: docker
    state: started
    enabled: yes